### ISSUE TITLE
Review of new mobile quickstarts

### ISSUE THREAD

**Issue by sgilda** [jboss-developer/jboss-unifiedpush-quickstarts#1]
1. _Important_ - The title should begin with the quickstart folder name, followed by a colon, then followed by a very short description. The 'Summary' metadata tag is for the longer description. The jboss website and QS tools use the text before the ':' to figure out the quickstart folder name and I'm not sure they will parse it correctly withe the leading '#'. For example, change the title for the push-contacts-mobile to:
   
   ```
   push-contacts-mobile: Push Contacts Mobile
   =========================== 
   ```
2.  I find the `push-contacts-mobile` quickstart README confusing. 
   - This folder contains 4 client applications and 2 server applications. I understand one server app is dependent on the other. It is not clear from this page how you build the pieces, what order to do it, or even how to get to the instructions for them. I think it's more the layout of the page and lack of links that's confusing. Maybe adding sections for the 'Server Applications' and 'Client Applications' would help. I will try to come up with something and email it or issue a pull. 
   - Is it possible to create a POM file in the root directory of this quickstart that will build all the pieces in the correct order, similar to the way the `inter-app` quickstart does it in EAP (see https://github.com/jboss-developer/jboss-eap-quickstarts)? 
   - The README file for this does not provide any instructions. The quickstart names should be links to the individual quickstart README files.
3. Instead of using '/path/to/', the other quickstarts use 'QUICKSTART_HOME for the path to the root directory of the quickstarts. For example, In the push-helloworld-android quickstart 'Customize and Build Application', step 1 would be:
   
   ```
   Open `QUICKSTART_HOME/push-helloworld-android/src/org/jboss/aerogear/unifiedpush/helloworld/Constants.java` for editing.
   ```
4. Have you run the QS tools checker (mvn -U org.jboss.maven.plugins:qstools:check) against the root directory of this project? I found a number of private API violations and a few README metadata issues. Also found property values issues with the push-contacts-mobile/client/push-contacts-mobile-android/pom.xml file.
5. If you want to share the script to build README.html from README.md, you need to replace the '```' in the markdown files. The script can't seem to handle that syntax. For example, replace: 

``` shell
For Linux:   EAP_HOME/bin/standalone.sh -Djboss.socket.binding.port-offset=200
For Windows: EAP_HOME\bin\standalone.bat -Djboss.socket.binding.port-offset=200
```

with

```
    For Linux:   EAP_HOME/bin/standalone.sh -Djboss.socket.binding.port-offset=200
    For Windows: EAP_HOME\bin\standalone.bat -Djboss.socket.binding.port-offset=200
```

**Comment by vibe13** [comment]
All the remaining issues have been resolved after merge of https://github.com/jboss-developer/jboss-mobile-quickstarts/pull/2. Thanks @sgilda !
